project_id = "ibxzyodvtmagnetpyyfz"

[functions.extract-documento]
verify_jwt = false

[functions.extract-extrato]
verify_jwt = false

[functions.generate-sugestoes]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.public-estoque]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.proxy-asaas]
verify_jwt = false

[functions.proxy-tiny]
verify_jwt = false

[functions.proxy-nuvemshop]
verify_jwt = false

[functions.proxy-meta]
verify_jwt = false

[functions.proxy-perfit]
verify_jwt = false

[functions.sync-vendas]
verify_jwt = false
